### ISSUE TITLE
exception ID_FS_VERSION is not iterable for non-LVM image

### ISSUE THREAD

**Issue by infinitewarp** [cloudigrade/houndigrade#121]
## Summary

Inspection appears to crash out when given a regular old not-LVM image.

## Steps to Reproduce

- run an instance in a customer AWS account using our old hand-crafted  "rhel8-faked-from-centos7" images.
  - for example, our dev02 account has a copy of this as `ami-01d6971d4709098f9`
- do the usual cloudigrade account setup, etc.
- ensure you have defined
  - `HOUNDIGRADE_ECS_IMAGE_NAME=quay.io/cloudservices/houndigrade`
  - ...and using the default `latest` tag
- eventually when celery runs the `launch_inspection_instance` task like…
  `celery --app config --workdir cloudigrade worker --concurrency 1 --task-events --queues launch_inspection_instance`

## Expected Result

- inspection runs normally and sends JSON to the SQS queue.

## Actual Result

- check the EC2 system log for the spawned cloud-init instance to find errors like:
```
[   37.736767] cloud-init[4456]: Block device attributes for drive "/dev/xvdbb"
[   37.744479] cloud-init[4456]: "Output:"
[   37.751968] cloud-init[4456]: "{'DEVNAME': '/dev/xvdbb', 'PTUUID': '000912ca', 'PTTYPE': 'dos'}"
[   37.760839] cloud-init[4456]: Device appears to have partitions, PTTYPE: dos
[   37.772771] cloud-init[4456]: Traceback (most recent call last):
[   37.784493] cloud-init[4456]: File "/opt/houndigrade/cli.py", line 900, in <module>
[   37.792434] cloud-init[4456]: main()
[   37.800511] cloud-init[4456]: File "/opt/houndigrade/.venv/lib/python3.9/site-packages/click/core.py", line 1137, in __call__
[   37.812689] cloud-init[4456]: return self.main(*args, **kwargs)
[   37.820317] cloud-init[4456]: File "/opt/houndigrade/.venv/lib/python3.9/site-packages/click/core.py", line 1062, in main
[   37.836344] cloud-init[4456]: rv = self.invoke(ctx)
[   37.843500] cloud-init[4456]: File "/opt/houndigrade/.venv/lib/python3.9/site-packages/click/core.py", line 1404, in invoke
[   37.864797] cloud-init[4456]: return ctx.invoke(self.callback, **ctx.params)
[   37.873828] cloud-init[4456]: File "/opt/houndigrade/.venv/lib/python3.9/site-packages/click/core.py", line 763, in invoke
[   37.883593] cloud-init[4456]: return __callback(*args, **kwargs)
[   37.887018] cloud-init[4456]: File "/opt/houndigrade/cli.py", line 72, in main
[   37.901779] cloud-init[4456]: mount_and_inspect(drive, image_id, results)
[   37.905866] cloud-init[4456]: File "/opt/houndigrade/cli.py", line 164, in mount_and_inspect
[   37.911319] cloud-init[4456]: if lvm_partitions := is_lvm(partitions):
[   37.918406] cloud-init[4456]: File "/opt/houndigrade/cli.py", line 592, in is_lvm
[   37.922878] cloud-init[4456]: if "LVM2" in properties.get("ID_FS_VERSION"):
[   37.927340] cloud-init[4456]: TypeError: argument of type 'NoneType' is not iterable
```

## Additional context

- likely introduced by https://github.com/cloudigrade/houndigrade/pull/119 for https://github.com/cloudigrade/houndigrade/issues/97

**Comment by infinitewarp** [comment]
I've tested this using the same account and image that triggered my original error, and the whole inspection process appears to be working correctly now. Thanks @katherine-black !
